# Generated by Django 2.2 on 2019-07-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img', upload_to='images'),
            preserve_default=False,
        ),
    ]
